apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xchild.example.org
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XChild
  resources:
    - name: vpc
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            region: us-west-1
            cidrBlock: 192.168.0.0/16
            enableDnsHostnames: true
            enableDnsSupport: true
      patches:
      - type: ToCompositeFieldPath
        fromFieldPath: status.atProvider.id
        toFieldPath: status.vpcid
