apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtargets.example.org
spec:
  group: example.org
  names:
    kind: XTarget
    plural: xtargets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - parameters
              properties:
                parameters:
                  type: object
                  description: Configuration parameters
                  properties:
                    vpcid:
                      type: string 
                  required:
                    - vpcid            
            status:
              type: object
              properties:
                vpcid:
                  type: string
                fromChild:
                  type: string
